### ISSUE TITLE
Epic: Prevent abusive value extraction from free accounts

### ISSUE THREAD

**Issue by bhazzard** [AntelopeIO/spring#1067]
Put in place preventative measures to prevent value extraction from subsidized/free account creation tools.

Ideas discussed so far:
- RAM Floor - prevent accounts from selling RAM below a certain threshold
- Encumbered RAM - Allow gifting RAM that can only be transferred back to / sold by the gifter

To decide between these:
- Work breakdown for Encumbered RAM
- Analyze expected RAM overhead of each solution
```[tasklist]
### Tasks
- [ ] https://github.com/AntelopeIO/spring/issues/1097
- [ ] https://github.com/AntelopeIO/reference-contracts/issues/108
- [ ] https://github.com/AntelopeIO/reference-contracts/issues/109
- [ ] https://github.com/eosnetworkfoundation/eos-system-contracts/issues/166
```
