### ISSUE TITLE
Stream constant token transfers to Beta testnet

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/spring#309]
On an AWS host, setup a Spring instance Peer'd into the Beta test net. Then run `trx_generator` on a cron every 2 minutes for 4-6 accounts to perform 60 transfer a minute. 

```[tasklist]
### Tasks
- [x] Spin up AWS host
- [x] Write shell script to build/install antelope software
- [x] Setup configuration to peer into Beta testnet and run Nodeos
- [x] Write shell script to run `trx_generator`
- [x] cron trx geneator to run every even minute
```

**Comment by ericpassmore** [comment]
completed, do not have permission to monitor or send email (no ses access).
