### ISSUE TITLE
EPIC: RAM Optimizations - Part 1

### ISSUE THREAD

**Issue by bhazzard** [AntelopeIO/spring#886]
```[tasklist]
### Tasks
- [ ] https://github.com/AntelopeIO/spring/issues/887
- [ ] https://github.com/AntelopeIO/spring/issues/936
- [ ] eosnetworkfoundation/engineering#111
- [ ] https://github.com/AntelopeIO/spring/issues/974
```
