### ISSUE TITLE
EPIC: OC for Designated Smart Contracts

### ISSUE THREAD

**Issue by bhazzard** [AntelopeIO/spring#888]
Decision: whitelist by account suffix in config.ini with default for *.xsat

```[tasklist]
### v1.1.0-rc1
- [ ] https://github.com/AntelopeIO/spring/issues/889
- [ ] https://github.com/AntelopeIO/spring/issues/981
- [ ] https://github.com/AntelopeIO/spring/issues/984
- [ ] https://github.com/AntelopeIO/spring/issues/985
- [ ] https://github.com/AntelopeIO/spring/issues/1039
- [ ] https://github.com/AntelopeIO/spring/issues/1040
```

```[tasklist]
### v1.1.0 Cusp
- [ ] https://github.com/AntelopeIO/spring/issues/986
- [ ] https://github.com/AntelopeIO/spring/issues/987
```

**Comment by heifner** [comment]
Complete
